import type { ToolAuthorizationDeclaration } from "../domain/tool-catalog";

export const TOOL_AUTH_DECLARATIONS: Record<string, ToolAuthorizationDeclaration> = {
  tool_search: { access: "anyone", behavior: "role-sensitive", note: "Visible tools depend on the active profile." },
  tool_result_read: { access: "anyone", behavior: "role-sensitive", note: "Stored tool-result refs are scoped to the active conversation or worker session unless the operator reads them directly." },
  run_tool_program: { access: "anyone", behavior: "role-sensitive", note: "The callable tool bundle is filtered by profile." },
  job_list: { access: "anyone", behavior: "role-sensitive", note: "Only jobs attached to accessible projects are listed." },
  job_get: { access: "anyone", behavior: "role-sensitive", note: "Only jobs attached to accessible projects are readable." },
  work_summary: { access: "anyone", behavior: "role-sensitive", note: "Work summaries only include projects and jobs visible to the active profile." },
  project_list: { access: "anyone", behavior: "role-sensitive", note: "Only projects allowed by role are listed." },
  project_get: { access: "anyone", behavior: "role-sensitive", note: "Only projects allowed by role are readable." },
  profile_list_launchable: { access: "anyone", behavior: "role-sensitive", note: "Returned profiles are limited to subagent targets the active profile can launch." },
  profile_set_defaults: { access: "anyone", behavior: "role-sensitive", note: "Only launchable target profiles can be updated, and model ids are validated against the target profile's live provider catalog before both profile defaults and stored runtime selection are synced." },
  conversation_search: { access: "anyone", behavior: "role-sensitive", note: "Results are limited to the append-only conversation archive for the active profile." },
  routine_check: { access: "anyone", behavior: "uniform" },
  routine_list: { access: "anyone", behavior: "uniform" },
  routine_get: { access: "anyone", behavior: "uniform" },
  routine_add: { access: "anyone", behavior: "uniform" },
  routine_update: { access: "anyone", behavior: "uniform" },
  routine_delete: { access: "anyone", behavior: "uniform" },
  set_alarm: { access: "anyone", behavior: "uniform" },
  set_timer: { access: "anyone", behavior: "uniform" },
  alarm_list: { access: "anyone", behavior: "uniform" },
  alarm_cancel: { access: "anyone", behavior: "uniform" },
  tickets_list: { access: "anyone", behavior: "uniform", note: "Reads the external Elinaro Tickets tracker through the configured API URL or SSH tunnel." },
  tickets_get: { access: "anyone", behavior: "uniform", note: "Reads one ticket from the external Elinaro Tickets tracker." },
  tickets_create: { access: "anyone", behavior: "uniform", note: "Creates a ticket in the external Elinaro Tickets tracker." },
  tickets_update: { access: "anyone", behavior: "uniform", note: "Updates a ticket in the external Elinaro Tickets tracker." },
  finance_summary: { access: "anyone", behavior: "uniform" },
  finance_budget: { access: "anyone", behavior: "uniform" },
  finance_history: { access: "anyone", behavior: "uniform" },
  finance_review: { access: "anyone", behavior: "uniform" },
  finance_import: { access: "anyone", behavior: "uniform" },
  finance_manage: { access: "anyone", behavior: "uniform" },
  finance_forecast: { access: "anyone", behavior: "uniform" },
  health_summary: { access: "anyone", behavior: "uniform" },
  health_history: { access: "anyone", behavior: "uniform" },
  health_log_checkin: { access: "anyone", behavior: "uniform" },
  email: { access: "root", behavior: "uniform", note: "Reads and sends mail through the configured mailbox account and may mark messages as read." },
  communications_status: { access: "root", behavior: "uniform", note: "Reads Vonage communications setup status and the webhook URLs exposed by the local HTTP listener." },
  make_phone_call: { access: "root", behavior: "uniform", note: "Places an outbound Vonage phone call using either the Gemini Live or local Kokoro/Whisper backend and writes the live transcript to disk." },
  call_create: { access: "root", behavior: "uniform", note: "Places outbound Vonage phone calls using the configured application keypair." },
  call_list: { access: "root", behavior: "uniform", note: "Reads persisted and fetched Vonage call records, including inbound webhook events." },
  call_get: { access: "root", behavior: "uniform", note: "Reads one Vonage call record and may refresh it from the remote API." },
  call_control: { access: "root", behavior: "uniform", note: "Controls a live Vonage call by altering media or transferring the destination." },
  message_send: { access: "root", behavior: "uniform", note: "Sends outbound Vonage messages over SMS, MMS, WhatsApp, Messenger, or Viber." },
  message_list: { access: "root", behavior: "uniform", note: "Reads persisted Vonage inbound, outbound, and status message records." },
  message_get: { access: "root", behavior: "uniform", note: "Reads one persisted Vonage message record." },
  routine_done: { access: "anyone", behavior: "uniform" },
  routine_undo_done: { access: "anyone", behavior: "uniform" },
  routine_snooze: { access: "anyone", behavior: "uniform" },
  routine_skip: { access: "anyone", behavior: "uniform" },
  routine_pause: { access: "anyone", behavior: "uniform" },
  routine_resume: { access: "anyone", behavior: "uniform" },
  model: { access: "anyone", behavior: "uniform" },
  think: { access: "anyone", behavior: "uniform" },
  extended_context: { access: "anyone", behavior: "uniform" },
  model_list_provider_models: { access: "anyone", behavior: "uniform" },
  model_select_active: { access: "anyone", behavior: "uniform" },
  context: { access: "anyone", behavior: "role-sensitive", note: "Project and profile context are filtered by role." },
  usage_summary: { access: "anyone", behavior: "role-sensitive", note: "Usage and cost summaries are limited to the active profile's model-usage ledger records." },
  model_context_usage: { access: "anyone", behavior: "uniform" },
  git_status: { access: "anyone", behavior: "role-sensitive", note: "Runs through the active profile's local or SSH shell backend and only within allowed repo/workspace paths." },
  git_diff: { access: "anyone", behavior: "role-sensitive", note: "Runs through the active profile's local or SSH shell backend and only within allowed repo/workspace paths." },
  git_stage: { access: "anyone", behavior: "role-sensitive", note: "Runs through the active profile's local or SSH shell backend and only within allowed repo/workspace paths." },
  git_commit: { access: "anyone", behavior: "role-sensitive", note: "Runs through the active profile's local or SSH shell backend and only within allowed repo/workspace paths." },
  git_revert: { access: "anyone", behavior: "role-sensitive", note: "Restores uncommitted changes for explicit paths through the active profile's local or SSH shell backend." },
  read_file: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  write_file: { access: "anyone", behavior: "role-sensitive", note: "Filesystem writes are restricted by project and memory permissions." },
  edit_file: { access: "anyone", behavior: "role-sensitive", note: "Filesystem edits are restricted by project and memory permissions." },
  multi_edit: { access: "anyone", behavior: "role-sensitive", note: "Filesystem edits are restricted by project and memory permissions." },
  apply_patch: { access: "anyone", behavior: "role-sensitive", note: "Filesystem patch application is restricted by project and memory permissions." },
  list_dir: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  glob: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  grep: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  stat_path: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  mkdir: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  move_path: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  copy_path: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  delete_path: { access: "anyone", behavior: "role-sensitive", note: "Filesystem paths are restricted by project and memory permissions." },
  memory_import: { access: "anyone", behavior: "role-sensitive", note: "Memory is written under the active profile namespace." },
  memory_search: { access: "anyone", behavior: "role-sensitive", note: "Memory results are limited to the active profile namespace." },
  telemetry_query: { access: "root", behavior: "uniform" },
  web_search: { access: "anyone", behavior: "uniform" },
  web_fetch: { access: "anyone", behavior: "uniform" },
  media_list: { access: "root", behavior: "uniform", note: "Reads the local tagged media library under the runtime media/ directory." },
  media_list_speakers: { access: "root", behavior: "uniform", note: "Inspects local output devices and configured speaker aliases." },
  media_play: { access: "root", behavior: "uniform", note: "Controls local audio playback and speaker routing on this machine." },
  media_pause: { access: "root", behavior: "uniform", note: "Controls local audio playback and speaker routing on this machine." },
  media_stop: { access: "root", behavior: "uniform", note: "Controls local audio playback and speaker routing on this machine." },
  media_set_volume: { access: "root", behavior: "uniform", note: "Controls local audio playback volume on this machine." },
  media_status: { access: "root", behavior: "uniform", note: "Reads local audio playback state from the managed mpv player." },
  todo_read: { access: "anyone", behavior: "uniform", note: "Reads the agent-managed session task list for the active conversation or worker session." },
  todo_write: { access: "anyone", behavior: "uniform", note: "Writes the agent-managed session task list for the active conversation or worker session." },
  openbrowser: { access: "root", behavior: "uniform", note: "Launches a local browser session and may write screenshot artifacts to disk." },
  secret_list: { access: "root", behavior: "uniform", note: "Lists local secret-store metadata for the active root profile without revealing secret values." },
  secret_import_file: { access: "root", behavior: "uniform", note: "Imports a flat JSON secret payload from a local file into the local secret store." },
  secret_generate_password: { access: "root", behavior: "uniform", note: "Generates a strong password server-side and stores it in the local secret store without returning the raw password." },
  secret_delete: { access: "root", behavior: "uniform", note: "Deletes one stored secret from the local secret store." },
  feature_manage: { access: "root", behavior: "uniform", note: "Reads and writes optional feature config blocks and may restart the managed service." },
  memory_reindex: { access: "anyone", behavior: "role-sensitive", note: "Reindexing only sees memory visible to the active profile." },
  reflect: { access: "anyone", behavior: "role-sensitive", note: "Reflection entries are written under the active profile memory namespace." },
  compact: { access: "anyone", behavior: "role-sensitive", note: "Durable memory writes land in the active profile namespace." },
  reload: { access: "anyone", behavior: "uniform" },
  new: { access: "anyone", behavior: "role-sensitive", note: "Durable memory writes land in the active profile namespace." },
  fnew: { access: "anyone", behavior: "role-sensitive", note: "Starts a fresh chat in the active conversation namespace without durable memory writes." },
  benchmark: { access: "anyone", behavior: "role-sensitive", note: "Benchmark uses the active profile model and memory index." },
  exec_command: { access: "anyone", behavior: "role-sensitive", note: "Non-root profiles run shell commands through their configured local shellUser or SSH execution backend, when present." },
  exec_status: { access: "anyone", behavior: "role-sensitive", note: "Background shell job visibility follows the active profile's shell access." },
  exec_output: { access: "anyone", behavior: "role-sensitive", note: "Background shell output visibility follows the active profile's shell access." },
  service_version: { access: "anyone", behavior: "uniform", note: "Reads the stamped deploy version metadata for the current runtime." },
  service_changelog_since_version: { access: "anyone", behavior: "uniform", note: "Reads deploy changelog entries whose version is numerically newer than a requested version for the current runtime." },
  service_healthcheck: { access: "root", behavior: "uniform", note: "Sends a simulated healthcheck message through the live local agent process and waits for HEALTHCHECK_OK." },
  update_preview: { access: "root", behavior: "uniform", note: "Reads the prepared source-root update metadata and changelog entries newer than the running service version." },
  update: { access: "root", behavior: "uniform", note: "Applies the latest prepared local update to the managed service, runs the healthcheck, and rolls back on failure." },
  service_rollback: { access: "root", behavior: "uniform", note: "Restarts the managed service on the previous release and verifies it with the healthcheck." },
  launch_coding_agent: { access: "anyone", behavior: "role-sensitive", note: "Subagent profile selection is restricted by the caller's roles." },
  resume_coding_agent: { access: "anyone", behavior: "role-sensitive", note: "Only coding-agent runs visible to the active profile can be resumed with follow-up instructions." },
  steer_coding_agent: { access: "anyone", behavior: "role-sensitive", note: "Only coding-agent runs visible to the active profile can receive mid-run steering instructions." },
  cancel_coding_agent: { access: "anyone", behavior: "role-sensitive", note: "Only coding-agent runs visible to the active profile can be cancelled." },
  workflow_status: { access: "anyone", behavior: "role-sensitive", note: "Only runs visible to the active profile are returned." },
};

export function getToolAuthorizationDeclaration(name: string): ToolAuthorizationDeclaration {
  const declaration = TOOL_AUTH_DECLARATIONS[name];
  if (!declaration) {
    throw new Error(`Missing tool authorization declaration for ${name}`);
  }
  return declaration;
}

export function assertToolAuthorizationCoverage(toolNames: string[]) {
  const missing = toolNames.filter((name) => !TOOL_AUTH_DECLARATIONS[name]);
  if (missing.length > 0) {
    throw new Error(`Missing tool authorization declarations for: ${missing.sort().join(", ")}`);
  }
}
